### PR TITLE
Implement "mapSplitter"

### PR DESCRIPTION
**Pull request by eayus**
Implement #21

### CODE REVIEW

**Comment by byorgey** [comment]
Looks good to me, thanks!  I think the CI is failing because the `toLower` in the doctest is not in scope.  Adding `>>> import Data.Char (toLower)` to the doctest ought to fix it.

**Comment by eayus** [comment]
Oh whoops, hopefully that fixes the issue.

**Comment by byorgey** [comment]
Thanks!

**Comment by byorgey** [comment]
Released to Hackage as part of `split-0.2.5`.

**Pull request merged**
