### PR TITLE
Support GHC 8.8

### PR DESCRIPTION
**Pull request by fumieval**
Pardon an automatically-posted pull request; this is a part of [Operation Vanguard](https://github.com/haskell-vanguard/haskell-vanguard). Note that this does not guarantee that tests and benchmarks are buildable.

### CODE REVIEW

**Comment by asr** [comment]
I couldn't install `split` with GHC 8.8.1-alpha. It seems this PR fixes the problem.

Blocking https://github.com/agda/agda/issues/3725.

**Comment by asr** [comment]
Thanks for merging. Please make a release including this PR.

**Comment by byorgey** [comment]
@asr Done, apologies for the delay!

**Comment by asr** [comment]
Thanks for releasing!

**Pull request merged**
